/* Node Hub V1 - Admin Upland connection flow aligned with member dashboard. */
(function(){
 const FUNCTION_NAME='upland-connect';let pollTimer=null;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 async function read(){if(!window.db||!window.currentUser)return null;const{data,error}=await db.functions.invoke(FUNCTION_NAME,{body:{action:'status'}});if(error)throw error;return data?.success?{status:data.status,connection_code:data.code||null,upland_user_id:data.upland_user_id||null,connected_at:data.connected_at||null}:null}
 function stop(){if(pollTimer)clearInterval(pollTimer);pollTimer=null}
 function render(c){const box=document.getElementById('admin-upland-account');if(!box)return; if(c?.status==='connected'){stop();box.innerHTML='<span class="eyebrow">UPLAND ACCOUNT</span><h2 style="margin-top:8px">Upland Account</h2><p style="color:#2563eb;font-weight:700;font-size:18px;margin-top:14px">✓ Upland Account Connected</p>';return} box.innerHTML='<span class="eyebrow">UPLAND ACCOUNT</span><h2 style="margin-top:8px">Connect Upland Account</h2><p>Authorize your Upland account with Node Hub to enable Upland API features.</p><button id="admin-upland-connect" class="button button-primary" type="button">Connect Upland Account</button><p id="admin-upland-message" style="margin-top:14px"></p>';document.getElementById('admin-upland-connect').onclick=start}
 async function refresh(){try{const c=await read();render(c);if(c?.status==='pending'){stop();pollTimer=setInterval(refresh,2000)}}catch(e){console.error('Admin Upland status:',e)}}
 async function start(){const b=document.getElementById('admin-upland-connect'),m=document.getElementById('admin-upland-message');if(b){b.disabled=true;b.textContent='Generating code...'}try{const existing=await read();if(existing?.status==='connected'||(existing?.status==='pending'&&existing.connection_code)){render(existing);if(existing.status==='pending')pollTimer=setInterval(refresh,2000);return}const{data,error}=await db.functions.invoke(FUNCTION_NAME,{body:{action:'generate'}});if(error)throw error;if(data?.status==='connected'){render(data);return}if(!data?.code)throw new Error(data?.error||'Upland did not return a connection code.');render({status:'pending',connection_code:data.code});pollTimer=setInterval(refresh,2000)}catch(e){console.error('Admin Upland connection:',e);if(m)m.textContent=e?.message||'Unable to generate an Upland connection code.';if(b){b.disabled=false;b.textContent='Connect Upland Account'}}}
 window.refreshAdminUplandStatus=refresh;refresh();
})();