// =====================================================
// NODE HUB V1
// Supabase + Authentication + Dashboard + Node Directory
// =====================================================
const SUPABASE_URL = "https://ynqtzyzxspoxssjrjeve.supabase.co";
const SUPABASE_KEY = "sb_publishable_FoDbr9qgVeeIYfzEZNNN9Q_53aHxI2g";
const { createClient } = supabase;
const db = createClient(SUPABASE_URL, SUPABASE_KEY);
let currentUser = null;
let nodes = [];
const nodeGrid=document.getElementById("node-grid"),nodeCount=document.getElementById("node-count"),searchInput=document.getElementById("node-search"),continentFilter=document.getElementById("continent-filter");
function escapeHTML(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function safeURL(v){try{const u=new URL(v);return ["http:","https:"].includes(u.protocol)?u.href:"#";}catch{return "#";}}
document.addEventListener("DOMContentLoaded",()=>{setupSearch();setupAuthForms();setupPasswordRecovery();removeAccountContact();setupLogout();setupNavigation();handleRoute();window.addEventListener("hashchange",handleRoute);setTimeout(loadNodes,0);initializeAuth().catch(e=>console.warn("Background authentication unavailable:",e));});
async function initializeAuth(){try{const result=await Promise.race([db.auth.getSession(),new Promise(r=>setTimeout(()=>r({data:{session:null},error:new Error("Authentication timeout")}),6000))]);const{data,error}=result||{};if(error)console.warn("Session unavailable:",error.message);currentUser=data?.session?.user||null;updateAuthUI();db.auth.onAuthStateChange((event,session)=>{currentUser=session?.user||null;updateAuthUI();if(event==="SIGNED_IN")setTimeout(()=>{updateDashboard?.();loadNodes();handleRoute();},0);if(event==="SIGNED_OUT"){removeDashboard?.();removeNodeProfile();setDashboardMode(false);}});}catch(e){console.warn("Authentication initialization unavailable:",e);}}
async function getCurrentRole(){if(!currentUser)return"user";try{const{data,error}=await db.from("profiles").select("role").eq("id",currentUser.id).maybeSingle();return error?"user":data?.role||"user";}catch{return"user";}}
async function routeAuthenticatedUser(){if(!currentUser){location.hash="login";return;}const role=await getCurrentRole();if(["owner","admin","moderator"].includes(role)){location.href="./admin.html";return;}if(typeof showDashboard==="function")showDashboard();}
function updateAuthUI(){const n=document.getElementById("auth-nav-text");if(n)n.textContent=currentUser?"Dashboard":"Sign in";const s=document.getElementById("account-status");if(s)s.textContent=currentUser?(currentUser.email||"Signed in"):"Not signed in";}
function setDashboardMode(active){const h=document.querySelector(".site-header"),sections=document.querySelectorAll("main > section");if(active){if(h)h.style.display="none";sections.forEach(s=>s.style.display="none");}else{if(h)h.style.display="";sections.forEach(s=>s.style.display="");}}
function getRoute(){return location.hash.replace(/^#/,'');}
async function handleRoute(){const raw=getRoute();const hash=raw.toLowerCase();if(hash.startsWith("node/")){setDashboardMode(false);removeDashboard?.();showNodeProfile(decodeURIComponent(raw.substring(5)));return;}if(hash.startsWith("reset-password")){setDashboardMode(false);removeDashboard?.();await showResetPassword();return;}removeNodeProfile();if(hash==="dashboard"||hash==="register"){if(!currentUser){location.hash="login";return;}await routeAuthenticatedUser();if(hash==="register"&&currentUser&&!(["owner","admin","moderator"].includes(await getCurrentRole())))setTimeout(()=>document.getElementById("dashboard-node-form")?.scrollIntoView({behavior:"smooth"}),100);return;}setDashboardMode(false);if(hash==="login"&&currentUser)await routeAuthenticatedUser();}
function setupNavigation(){document.addEventListener("click",e=>{const l=e.target.closest("a[href]");if(!l)return;const h=l.getAttribute("href");if(h==="#submit"){e.preventDefault();location.hash=currentUser?"register":"login";}if(h==="#login"&&currentUser){e.preventDefault();location.hash="dashboard";}});}
async function loadNodes(){if(!nodeGrid)return;try{const r=await Promise.race([db.from("nodes").select("*").eq("status","approved").order("created_at",{ascending:false}),new Promise(r=>setTimeout(()=>r({data:null,error:new Error("Directory timeout")}),8000))]);const{data,error}=r||{};if(error){console.error("Directory:",error);showDirectoryError();return;}nodes=data||[];renderNodes(nodes);renderWorldMap(nodes);}catch(e){console.error("Directory:",e);showDirectoryError();}}
function renderNodes(list){if(!nodeGrid)return;nodeGrid.innerHTML="";if(nodeCount)nodeCount.textContent=`${list.length} ${list.length===1?"Node":"Nodes"}`;if(!list.length){showEmptyDirectory();return;}list.forEach(n=>nodeGrid.appendChild(createNodeCard(n)));}
function createNodeCard(n){const a=document.createElement("article");a.className="node-card";const logo=n.logo_url||n.image_url||"";const image=logo?`<div class="node-card-image"><img src="${escapeHTML(logo)}" alt="${escapeHTML(n.name||"Node")}" loading="lazy"></div>`:`<div class="node-card-image node-card-placeholder">●</div>`;a.innerHTML=`${image}<div class="node-card-content"><h3>${escapeHTML(n.name||"Unnamed Node")}</h3><p class="node-location">${escapeHTML(n.city||"")}${n.country?`, ${escapeHTML(n.country)}`:""}</p>${n.upland_location?`<p class="node-upland-location"><strong>Neighborhood:</strong> ${escapeHTML(n.upland_location)}</p>`:""}<div class="node-links" style="justify-content:center;">${n.discord_url?`<a href="${safeURL(n.discord_url)}" target="_blank" rel="noopener noreferrer">Discord</a>`:""}${n.telegram_url?`<a href="${safeURL(n.telegram_url)}" target="_blank" rel="noopener noreferrer">Telegram</a>`:""}${n.twitter_url?`<a href="${safeURL(n.twitter_url)}" target="_blank" rel="noopener noreferrer">X / Twitter</a>`:""}</div><div style="text-align:center;margin-top:18px;"><a class="node-profile-link" href="#node/${encodeURIComponent(n.id)}">View Node Profile</a></div><div class="node-card-footer" style="justify-content:center;margin-top:16px;"><span class="verified-badge">✓ Verified Node</span></div></div>`;return a;}
function showEmptyDirectory(){if(!nodeGrid)return;nodeGrid.innerHTML=`<div class="empty-directory"><div class="empty-icon">◉</div><h3>No Nodes listed yet</h3><p>Be one of the first Node administrators to register your Node.</p><a href="#submit" class="button button-primary">Submit a Node</a></div>`;if(nodeCount)nodeCount.textContent="0 Nodes";}
function showDirectoryError(){if(!nodeGrid)return;nodeGrid.innerHTML=`<div class="empty-directory"><div class="empty-icon">!</div><h3>Directory temporarily unavailable</h3><p>The Node directory is taking too long to respond. The rest of Node Hub remains available.</p><button class="button button-secondary" type="button" onclick="loadNodes()">Try again</button></div>`;}
function setupSearch(){searchInput?.addEventListener("input",filterNodes);continentFilter?.addEventListener("change",filterNodes);}
function filterNodes(){const s=searchInput?.value.trim().toLowerCase()||"",c=continentFilter?.value||"";renderNodes(nodes.filter(n=>{const t=[n.name,n.city,n.country,n.upland_location,n.description].filter(Boolean).join(" ").toLowerCase();return(!s||t.includes(s))&&(!c||n.continent===c);}));}
function renderWorldMap(list){const canvas=document.getElementById("node-map-canvas"),listEl=document.getElementById("node-map-list"),stats=document.getElementById("node-map-stats");if(!canvas)return;if(stats)stats.textContent="";if(listEl)listEl.innerHTML="";canvas.innerHTML="";if(!list.length){canvas.innerHTML=`<div class="node-map-empty">No verified Nodes yet.</div>`;return;}const dots=list.map(n=>{const hash=String(n.id||n.name||"").split("").reduce((x,ch)=>(x*31+ch.charCodeAt(0))>>>0,7);const left=10+(hash%80),top=15+((hash>>>8)%65);const neighborhood=n.upland_location||n.neighborhood||"Node location";return `<a href="#node/${encodeURIComponent(n.id)}" aria-label="${escapeHTML(neighborhood)}" title="${escapeHTML(neighborhood)}" style="position:absolute;left:${left}%;top:${top}%;width:11px;height:11px;border-radius:50%;background:var(--accent-light);box-shadow:0 0 0 5px rgba(255,132,0,.14);z-index:2;"></a>`;}).join("");canvas.innerHTML=`<div style="position:absolute;inset:18% 10%;border:1px solid rgba(255,255,255,.08);border-radius:48%;transform:rotate(-8deg);"></div><div style="position:absolute;inset:28% 18%;border:1px solid rgba(255,255,255,.06);border-radius:42%;transform:rotate(12deg);"></div>${dots}`;}
function setupAuthForms(){document.getElementById("signup-form")?.addEventListener("submit",e=>{e.preventDefault();signUp();});document.getElementById("login-form")?.addEventListener("submit",e=>{e.preventDefault();signIn();});}
function setupPasswordRecovery(){const form=document.getElementById("login-form");if(!form)return;const password=document.getElementById("login-password");if(!password)return;const link=document.createElement("a");link.href="#";link.id="forgot-password-link";link.textContent="Forgot your password?";link.style.display="block";link.style.marginTop="10px";link.style.textAlign="right";link.addEventListener("click",async e=>{e.preventDefault();const email=document.getElementById("login-email")?.value.trim().toLowerCase()||"";if(!email){alert("Enter your email first, then click Forgot your password.");return;}try{const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:"https://nodehubupland.github.io/node-hub/#reset-password"});if(error){alert(error.message);return;}alert("Password recovery instructions were sent to your email.");}catch(err){console.error(err);alert("Unable to send password recovery instructions.");}});password.insertAdjacentElement("afterend",link);}
async function showResetPassword(){const old=document.getElementById("nodehub-reset-password");if(old)old.remove();const section=document.createElement("section");section.id="nodehub-reset-password";section.className="section section-alt";section.innerHTML=`<div class="container"><div class="auth-container"><div class="auth-card"><span class="eyebrow">NODE HUB ACCOUNT</span><h2>Reset Password</h2><p>Create a new password for your Node Hub account.</p><form id="reset-password-form"><label for="reset-password">New Password</label><input id="reset-password" type="password" minlength="8" placeholder="Minimum 8 characters" required><label for="reset-password-confirm">Confirm New Password</label><input id="reset-password-confirm" type="password" minlength="8" placeholder="Repeat your new password" required><button type="submit" class="button button-primary">Update Password</button></form><p id="reset-password-message" style="margin-top:16px;"></p></div></div></div>`;document.body.appendChild(section);section.scrollIntoView({behavior:"smooth"});const form=document.getElementById("reset-password-form");form.addEventListener("submit",async e=>{e.preventDefault();const p=document.getElementById("reset-password").value,c=document.getElementById("reset-password-confirm").value,m=document.getElementById("reset-password-message");if(p.length<8){m.textContent="Password must contain at least 8 characters.";return;}if(p!==c){m.textContent="Passwords do not match.";return;}try{const{data:sessionData}=await db.auth.getSession();if(!sessionData?.session){m.textContent="This recovery link is invalid or has expired. Please request a new one.";return;}const{error}=await db.auth.updateUser({password:p});if(error){m.textContent=error.message;return;}m.textContent="Password updated successfully. Redirecting to sign in...";setTimeout(async()=>{await db.auth.signOut();location.hash="login";},1200);}catch(err){console.error(err);m.textContent="Unable to update the password. Please request a new recovery email.";}});}
function removeAccountContact(){document.querySelector(".contact-account")?.remove();}
async function signUp(){const u=document.getElementById("signup-username")?.value.trim()||"",e=document.getElementById("signup-email")?.value.trim().toLowerCase()||"",p=document.getElementById("signup-password")?.value||"";if(!e||!p){alert("Please enter your email and password.");return;}if(p.length<8){alert("Password must contain at least 8 characters.");return;}try{const{data,error}=await db.auth.signUp({email:e,password:p,options:{emailRedirectTo:"https://nodehubupland.github.io/node-hub/",data:{username:u}}});if(error){alert(error.message);return;}if(data.user&&data.session){currentUser=data.user;await createProfile(u);updateAuthUI();location.hash="dashboard";}else if(data.user)alert("Account created. Please check your email to confirm your account.");}catch(e){console.error(e);alert("Unable to create your account.");}}
async function createProfile(u){if(!currentUser)return;try{await db.from("profiles").upsert({id:currentUser.id,username:u||currentUser.email?.split("@")[0]||"User",email:currentUser.email},{onConflict:"id"});}catch(e){console.warn("Profile creation error:",e);}}
async function signIn(){const e=document.getElementById("login-email")?.value.trim().toLowerCase()||"",p=document.getElementById("login-password")?.value||"",b=document.querySelector("#login-form button[type='submit']");if(!e||!p){alert("Please enter your email and password.");return;}const o=b?.textContent||"Sign in";try{if(b){b.disabled=true;b.textContent="Signing in...";}const{data,error}=await db.auth.signInWithPassword({email:e,password:p});if(error){alert(error.message);return;}currentUser=data.user;updateAuthUI();await routeAuthenticatedUser();}catch(e){console.error(e);alert("Unable to sign in.");}finally{if(b){b.disabled=false;b.textContent=o;}}}
async function signOut(){try{const{error}=await db.auth.signOut();if(error){alert(error.message);return;}currentUser=null;removeDashboard?.();removeNodeProfile();setDashboardMode(false);location.hash="home";}catch(e){console.error(e);}}
async function showNodeProfile(id){removeNodeProfile();const s=document.createElement("section");s.id="nodehub-node-profile";s.className="section section-alt";s.innerHTML=`<div class="container"><div class="auth-card"><span class="eyebrow">NODE PROFILE</span><h2>Loading Node...</h2><p>Loading verified Node information.</p></div></div>`;document.body.appendChild(s);s.scrollIntoView({behavior:"smooth"});try{const{data:n,error}=await db.from("nodes").select("*").eq("id",id).eq("status","approved").maybeSingle();if(error||!n){s.innerHTML=`<div class="container"><div class="auth-card"><h2>Node not found</h2><p>This Node is unavailable or has not been approved.</p><a href="#nodes" class="button button-primary">Back to Nodes</a></div></div>`;return;}const logo=n.logo_url||n.image_url||"";s.innerHTML=`<div class="container"><div class="auth-card" style="text-align:center;max-width:900px;margin:0 auto;">${logo?`<img src="${escapeHTML(logo)}" alt="${escapeHTML(n.name)}" style="display:block;width:min(280px,100%);max-height:280px;object-fit:contain;margin:0 auto 24px;">`:""}<span class="eyebrow">VERIFIED NODE</span><h2>${escapeHTML(n.name)}</h2><p>${escapeHTML(n.city||"")}${n.country?`, ${escapeHTML(n.country)}`:""}</p>${n.upland_location?`<p><strong>Neighborhood:</strong> ${escapeHTML(n.upland_location)}</p>`:""}${n.description?`<p>${escapeHTML(n.description)}</p>`:""}<div style="display:flex;flex-wrap:wrap;justify-content:center;gap:10px;margin-top:22px;">${n.upland_node_url?`<a class="button button-primary" href="${safeURL(n.upland_node_url)}" target="_blank" rel="noopener noreferrer">Open Node in Upland</a>`:""}${n.discord_url?`<a class="button button-secondary" href="${safeURL(n.discord_url)}" target="_blank" rel="noopener noreferrer">Discord</a>`:""}${n.telegram_url?`<a class="button button-secondary" href="${safeURL(n.telegram_url)}" target="_blank" rel="noopener noreferrer">Telegram</a>`:""}${n.twitter_url?`<a class="button button-secondary" href="${safeURL(n.twitter_url)}" target="_blank" rel="noopener noreferrer">X / Twitter</a>`:""}</div><div style="margin-top:24px;"><a href="#nodes">← Back to Nodes</a></div></div></div>`;}catch(e){console.error(e);s.innerHTML=`<div class="container"><div class="auth-card"><h2>Unable to load Node</h2><p>Please try again.</p><a href="#nodes" class="button button-primary">Back to Nodes</a></div></div>`;}}
function removeNodeProfile(){document.getElementById("nodehub-node-profile")?.remove();}
