(function () {
  'use strict';
  if (window.__NODEHUB_I18N_FIX__) return;
  window.__NODEHUB_I18N_FIX__ = true;

  const PT = {
    'UPLAND COMMUNITY DIRECTORY':'DIRETÓRIO DE COMUNIDADES UPLAND',
    'DIRECTORY':'DIRETÓRIO','WORLD MAP':'MAPA MUNDIAL','Node Hub World Map':'Mapa Mundial Node Hub',
    'Explore Nodes':'Explorar Nodes','Submit a Node':'Enviar um Node',
    'Discover Upland Nodes Around the World':'Descubra Nodes Upland pelo Mundo',
    'Find Nodes, connect with communities, discover their locations, and explore the people building Upland communities around the world.':'Encontre Nodes, conecte-se com comunidades, descubra suas localizações e conheça as pessoas que constroem comunidades Upland pelo mundo.',
    'Discover Nodes and their communities around the world.':'Descubra Nodes e suas comunidades pelo mundo.',
    'Find Nodes Across Upland':'Encontre Nodes pelo Upland','Explore Node locations around the world.':'Explore localizações de Nodes pelo mundo.',
    'Loading approved Nodes...':'Carregando Nodes aprovados...','Loading Nodes...':'Carregando Nodes...','Connecting to the Node Hub directory.':'Conectando ao diretório Node Hub.',
    'GROW THE DIRECTORY':'EXPANDA O DIRETÓRIO','Have a Node?':'Tem um Node?',
    'Register your Node for free. Your submission will be reviewed by the Node Hub team before appearing in the public directory.':'Cadastre seu Node gratuitamente. O cadastro será analisado pela equipe Node Hub antes de aparecer no diretório público.',
    'Register your Node':'Cadastre seu Node','Node registration is available through your Node Hub account.':'O cadastro do Node está disponível pela sua conta Node Hub.',
    'ABOUT NODE HUB':'SOBRE O NODE HUB','One place to discover Node communities.':'Um só lugar para descobrir comunidades Node.',
    'Node Hub is a community-built directory designed to help Upland players discover Nodes, learn about their communities, find their locations, and connect with their official social channels.':'O Node Hub é um diretório criado pela comunidade para ajudar jogadores de Upland a descobrir Nodes, conhecer suas comunidades, encontrar suas localizações e acessar seus canais sociais oficiais.',
    'Verified Information':'Informações Verificadas','Each Node profile is submitted by its administrator and reviewed by the Node Hub team before publication.':'Cada perfil de Node é enviado por seu administrador e analisado pela equipe Node Hub antes da publicação.',
    'Global Community':'Comunidade Global','Our goal is to make Nodes easier to discover across cities, countries and continents.':'Nosso objetivo é tornar os Nodes mais fáceis de encontrar em cidades, países e continentes.',
    'Connect':'Conectar','Discover official Discord, Telegram, X and other community channels from each Node profile.':'Descubra Discord, Telegram, X e outros canais oficiais de cada comunidade nos perfis dos Nodes.',
    'SUPPORT NODE HUB':'APOIE O NODE HUB','Help keep the project free.':'Ajude a manter o projeto gratuito.','Node Hub is being built as a free community platform. If you want to help with its maintenance and future development, you can support us.':'O Node Hub está sendo construído como uma plataforma gratuita da comunidade. Se quiser ajudar na manutenção e no desenvolvimento futuro, você pode nos apoiar.','Donate / Buy Me a Coffee':'Doar / Comprar um Café',
    'ROADMAP':'ROADMAP','Node Hub Evolution':'Evolução do Node Hub','The platform will continue to evolve with the community.':'A plataforma continuará evoluindo com a comunidade.',
    'Node Directory':'Diretório de Nodes','Community':'Comunidade','Ecosystem':'Ecossistema','Coming soon.':'Em breve.','Future development.':'Desenvolvimento futuro.',
    'Node registration':'Cadastro de Node','Manual verification':'Verificação manual','Verified Node profiles':'Perfis de Nodes verificados','Node administrator dashboard':'Painel administrativo do Node','Leader information':'Informações do líder','Node logo and images':'Logo e imagens do Node','Discord and social links':'Discord e links sociais','Node location':'Localização do Node','Worldwide directory':'Diretório mundial','Search and filtering':'Pesquisa e filtros','Node profile pages':'Páginas de perfil dos Nodes','World Map':'Mapa Mundial','English (US)':'Inglês (EUA)','Português (BR)':'Português (BR)','Mobile responsive interface':'Interface responsiva para celular','Upland API integration':'Integração com a API Upland','Connect Upland Account':'Conectar conta Upland','Upland authentication via API':'Autenticação Upland via API',
    'Advanced Node statistics':'Estatísticas avançadas dos Nodes','Community profiles and roles':'Perfis e funções da comunidade','Node activity and announcements':'Atividades e anúncios dos Nodes','Media galleries':'Galerias de mídia','Improved world map':'Mapa mundial aprimorado','Advanced Node discovery':'Descoberta avançada de Nodes','Featured Nodes':'Nodes em destaque','Community interaction':'Interação da comunidade','Node events and calendar':'Eventos e calendário dos Nodes','Leaderboards and community rankings':'Rankings e classificações da comunidade','Node news and updates':'Notícias e atualizações dos Nodes','Node analytics dashboard':'Painel de análise dos Nodes','Member and community insights':'Informações sobre membros e comunidades','Node search by city and neighborhood':'Pesquisa de Nodes por cidade e bairro','Node availability and status':'Disponibilidade e status dos Nodes',
    'Spark rental information':'Informações sobre aluguel de Spark','Spark rental marketplace tools':'Ferramentas de marketplace para aluguel de Spark','Property sale and listing information':'Informações sobre venda e anúncios de propriedades','Property discovery tools':'Ferramentas para descobrir propriedades','Advanced Node analytics':'Análises avançadas de Nodes','Community management tools':'Ferramentas de gestão da comunidade','Developer and builder resources':'Recursos para desenvolvedores e builders','Partner integrations':'Integrações com parceiros','Notifications and alerts':'Notificações e alertas','Advanced discovery and recommendations':'Descoberta e recomendações avançadas','Node ecosystem marketplace':'Marketplace do ecossistema Node','Cross-community tools':'Ferramentas entre comunidades',
    'NODE HUB ACCOUNT':'CONTA NODE HUB','Dashboard':'Painel','Connect your Upland account to continue.':'Conecte sua conta Upland para continuar.','Manage your Node Hub account and Node submissions.':'Gerencie sua conta Node Hub e seus Nodes enviados.','Sign out':'Sair','Back to Home':'Voltar para Home','YOUR NODES':'SEUS NODES','My Nodes':'Meus Nodes','NODE REGISTRATION':'CADASTRO DE NODE','Register My Node':'Cadastrar Meu Node','Node registration will be submitted for review by the Node Hub team.':'O cadastro será enviado para análise da equipe Node Hub.','Submit Node for Review':'Enviar Node para Análise','Cancel':'Cancelar','ACCOUNT INFORMATION':'INFORMAÇÕES DA CONTA','Username':'Nome de usuário','Email':'E-mail','Function':'Função','No Nodes registered yet.':'Nenhum Node cadastrado ainda.','Use Register My Node to submit your first Node.':'Use Cadastrar Meu Node para enviar seu primeiro Node.','Node Name':'Nome do Node','Description':'Descrição','City':'Cidade','Country':'País','Neighborhood':'Bairro','Enter the Neighborhood where your Node is located in Upland.':'Informe o bairro onde seu Node está localizado no Upland.','Continent':'Continente','Select continent':'Selecione o continente','North America':'América do Norte','South America':'América do Sul','Europe':'Europa','Asia':'Ásia','Africa':'África','Oceania':'Oceania','Node Logo':'Logo do Node','Discord':'Discord','Telegram':'Telegram','X / Twitter':'X / Twitter','Not signed in':'Não conectado','Sign in':'Entrar','Create an Account':'Criar uma Conta',
    'UPLAND ACCOUNT':'CONTA UPLAND','Connect your Upland account to Node Hub to enable Upland API features in your account.':'Conecte sua conta Upland ao Node Hub para habilitar os recursos da API Upland na sua conta.','How to connect your Upland account':'Como conectar sua conta Upland','Waiting for Upland to confirm the connection...':'Aguardando o Upland confirmar a conexão...','Copy Code':'Copiar código','REGISTER YOUR NODE':'CADASTRE SEU NODE','Have a Node? Register it here after connecting your Upland account.':'Tem um Node? Cadastre-o aqui depois de conectar sua conta Upland.','Back to Dashboard':'Voltar ao Painel','Upland Account Connected':'Conta Upland conectada','✓ Upland Account Connected':'✓ Conta Upland conectada','Loading...':'Carregando...',
    'All continents':'Todos os continentes','Search Nodes...':'Pesquisar Nodes...','Privacy Policy':'Política de Privacidade','All rights reserved.':'Todos os direitos reservados.','Contact':'Contato','Need help with your account?':'Precisa de ajuda com sua conta?','Contact Node Hub':'Entrar em contato com o Node Hub','Password':'Senha','Your password':'Sua senha','Minimum 8 characters':'Mínimo de 8 caracteres','Create Account':'Criar Conta','NEW TO NODE HUB?':'NOVO NO NODE HUB?','Sign in to manage your Node and access your dashboard.':'Entre para gerenciar seu Node e acessar seu painel.','Create your free account and submit your Node for verification.':'Crie sua conta gratuita e envie seu Node para verificação.',
    'Uploaded':'Enviado','Approved':'Aprovado','Rejected':'Rejeitado','Pending':'Pendente','Status':'Status','Submitted':'Enviado','Actions':'Ações','Location':'Localização','User':'Usuário','Refresh':'Atualizar','Approve':'Aprovar','Reject':'Rejeitar','Set Pending':'Definir como pendente','Set Approved':'Definir como aprovado','Set Rejected':'Definir como rejeitado','Loading':'Carregando','Submitting...':'Enviando...','Please complete Node Name, City, Country and Continent.':'Preencha Nome do Node, Cidade, País e Continente.','Could not register the Node':'Não foi possível cadastrar o Node','Node submitted successfully! It will be reviewed by the Node Hub team.':'Node enviado com sucesso! Ele será analisado pela equipe Node Hub.','Could not upload the Node image':'Não foi possível enviar a imagem do Node','Unable to submit the Node. Please try again.':'Não foi possível enviar o Node. Tente novamente.'
  };

  function language(){ return localStorage.getItem('nodehub-language') || document.getElementById('language-selector')?.value || 'en-US'; }

  function translate(root=document){
    if(language()!=='pt-BR') return;
    root.querySelectorAll?.('[data-i18n]').forEach(el=>{ const k=el.getAttribute('data-i18n'); if(PT[k]) el.textContent=PT[k]; });
    const walker=document.createTreeWalker(root===document?document.body:root,NodeFilter.SHOW_TEXT);
    const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(n=>{ const t=n.nodeValue.trim(); if(PT[t]) n.nodeValue=n.nodeValue.replace(t,PT[t]); });
    document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(el=>{ if(PT[el.placeholder]) el.placeholder=PT[el.placeholder]; });
  }

  function install(){
    const selector=document.getElementById('language-selector');
    if(selector){
      selector.addEventListener('change',()=>{ localStorage.setItem('nodehub-language',selector.value); setTimeout(()=>translate(),0); },true);
    }
    translate();
    new MutationObserver(mutations=>mutations.forEach(m=>m.addedNodes.forEach(n=>{ if(n.nodeType===1) translate(n); }))).observe(document.body,{childList:true,subtree:true});
  }

  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',install); else install();
})();
