// Node Hub stable frontend patch
(function(){'use strict';if(window.__NODEHUB_STABLE_PATCH__)return;window.__NODEHUB_STABLE_PATCH__=true;
const style=document.createElement('style');style.textContent=`.nodehub-discord-footer{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;margin-left:10px;vertical-align:middle;opacity:.9;transition:opacity .2s ease,transform .2s ease}.nodehub-discord-footer:hover{opacity:1;transform:translateY(-1px)}.nodehub-discord-footer svg{width:22px;height:22px;fill:currentColor}.nodehub-verified-upland{color:#3b82f6!important;font-weight:700!important}@media(max-width:760px){.hero.section{min-height:auto;padding-top:68px;padding-bottom:68px}}
.nodehub-carousel-grid{position:relative;overflow:visible;padding-left:58px;padding-right:58px}
.nodehub-carousel-grid .nodehub-carousel-arrow{position:absolute;top:50%;z-index:10;width:42px;height:42px;border:1px solid var(--border);border-radius:50%;background:var(--bg-card);color:var(--text);display:flex;align-items:center;justify-content:center;cursor:pointer;font-size:24px;line-height:1;transform:translateY(-50%);transition:background var(--transition),border-color var(--transition),color var(--transition),transform var(--transition);box-shadow:0 8px 24px rgba(0,0,0,.2)}
.nodehub-carousel-grid .nodehub-carousel-arrow:hover{background:var(--bg-card-hover);border-color:rgba(139,92,246,.45);color:var(--accent-light);transform:translateY(-50%) scale(1.04)}
.nodehub-carousel-grid .nodehub-carousel-prev{left:0}.nodehub-carousel-grid .nodehub-carousel-next{right:0}
.nodehub-carousel-grid .nodehub-carousel-arrow[hidden]{display:none}
@media(max-width:760px){.nodehub-carousel-grid{padding-left:46px;padding-right:46px}.nodehub-carousel-grid .nodehub-carousel-arrow{width:36px;height:36px;font-size:21px}.nodehub-carousel-grid{grid-template-columns:1fr}}
`;document.head.appendChild(style);
function addDiscordFooter(){const f=document.querySelector('.site-footer .container');if(!f||f.querySelector('.nodehub-discord-footer'))return;const a=document.createElement('a');a.className='nodehub-discord-footer';a.href='https://discord.gg/dtAFAvUbfX';a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label','Node Hub Discord');a.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19.54 5.1A16.9 16.9 0 0 0 15.35 3.8l-.52 1.06a15.5 15.5 0 0 0-5.66 0L8.65 3.8A16.9 16.9 0 0 0 4.46 5.1C1.81 9.08 1.09 12.96 1.45 16.78a17 17 0 0 0 5.15 2.61l1.24-1.7a10.8 10.8 0 0 1-1.96-.94l.48-.37c3.78 1.74 7.88 1.74 11.61 0l.49.37c-.63.37-1.29.69-1.97.94l1.24 1.7a17 17 0 0 0 5.15-2.61c.42-4.43-.72-8.27-3.34-11.68ZM8.43 14.45c-1.14 0-2.08-1.05-2.08-2.34s.92-2.34 2.08-2.34 2.09 1.05 2.08 2.34c0 1.29-.92 2.34-2.08 2.34Zm7.14 0c-1.14 0-2.08-1.05-2.08-2.34s.92-2.34 2.08-2.34 2.09 1.05 2.08 2.34c0 1.29-.92 2.34-2.08 2.34Z"/></svg>';f.appendChild(a)}
function markVerified(){const s=document.getElementById('dashboard-upland-status');if(s&&s.dataset.connected==='true')s.classList.add('nodehub-verified-upland')}
function loadOnce(src,id){if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;s.async=false;document.body.appendChild(s)}
let nodehubCarouselList=[];let nodehubCarouselStart=0;
function nodehubShuffle(list){const copy=[...list];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function nodehubCarouselLabels(){const pt=localStorage.getItem('nodehub-language')==='pt-BR';return pt?{prev:'Nodes anteriores',next:'Próximos Nodes'}:{prev:'Previous Nodes',next:'Next Nodes'};}
function nodehubEnsureCarouselButtons(){if(!nodeGrid||nodeGrid.querySelector('.nodehub-carousel-arrow'))return;nodeGrid.classList.add('nodehub-carousel-grid');const prev=document.createElement('button');prev.type='button';prev.className='nodehub-carousel-arrow nodehub-carousel-prev';prev.innerHTML='&#8249;';prev.addEventListener('click',()=>{if(nodehubCarouselList.length<=3)return;nodehubCarouselStart=(nodehubCarouselStart-1+nodehubCarouselList.length)%nodehubCarouselList.length;nodehubRenderCarousel();});const next=document.createElement('button');next.type='button';next.className='nodehub-carousel-arrow nodehub-carousel-next';next.innerHTML='&#8250;';next.addEventListener('click',()=>{if(nodehubCarouselList.length<=3)return;nodehubCarouselStart=(nodehubCarouselStart+1)%nodehubCarouselList.length;nodehubRenderCarousel();});nodeGrid.appendChild(prev);nodeGrid.appendChild(next);}
function nodehubRenderCarousel(){if(!nodeGrid)return;nodehubEnsureCarouselButtons();const prev=nodeGrid.querySelector('.nodehub-carousel-prev'),next=nodeGrid.querySelector('.nodehub-carousel-next');const labels=nodehubCarouselLabels();if(prev){prev.setAttribute('aria-label',labels.prev);prev.title=labels.prev;}if(next){next.setAttribute('aria-label',labels.next);next.title=labels.next;}nodeGrid.querySelectorAll('.node-card').forEach(card=>card.remove());if(!nodehubCarouselList.length){showEmptyDirectory();if(prev)prev.hidden=true;if(next)next.hidden=true;return;}const visible=[];const count=Math.min(3,nodehubCarouselList.length);for(let i=0;i<count;i++)visible.push(nodehubCarouselList[(nodehubCarouselStart+i)%nodehubCarouselList.length]);visible.forEach(n=>nodeGrid.insertBefore(createNodeCard(n),prev||null));if(prev)prev.hidden=nodehubCarouselList.length<=3;if(next)next.hidden=nodehubCarouselList.length<=3;}
function nodehubRenderNodes(list){if(!nodeGrid)return;const isInitialDirectory=list===nodes;if(isInitialDirectory){nodehubCarouselList=nodehubShuffle(list);nodehubCarouselStart=0;}else{nodehubCarouselList=[...list];nodehubCarouselStart=0;}if(nodeCount)nodeCount.textContent=`${list.length} ${list.length===1?'Node':'Nodes'}`;nodehubRenderCarousel();}
function setupNodeCarousel(){if(typeof nodeGrid==='undefined'||!nodeGrid)return;window.renderNodes=nodehubRenderNodes;nodehubEnsureCarouselButtons();}
function addTreasureButton(){const card=document.getElementById('upland-account-card');if(!card||document.getElementById('nodehub-treasure-card'))return;const box=document.createElement('div');box.id='nodehub-treasure-card';box.className='auth-card';box.style.cssText='max-width:900px;margin:0 auto 24px';box.innerHTML='<span class="eyebrow">MY TREASURE REPORT</span><h2 style="margin-top:8px">My Treasure Report</h2><p id="nodehub-treasure-description">View your personal Treasure history and statistics.</p><div style="margin-top:16px"><a id="nodehub-treasure-link" class="button button-primary" href="./treasure-report.html">View My Treasure Report</a></div>';card.parentNode.insertBefore(box,card.nextElementSibling);updateTreasureButton();}
function updateTreasureButton(){const box=document.getElementById('nodehub-treasure-card');if(!box)return;const s=document.getElementById('dashboard-upland-status');const d=document.getElementById('nodehub-treasure-description');const a=document.getElementById('nodehub-treasure-link');const connected=s?.dataset.connected==='true';const pt=localStorage.getItem('nodehub-language')==='pt-BR';if(connected){d.textContent=pt?'Sua conta Upland já está conectada. Abra seu relatório pessoal.':'Your Upland account is already connected. Open your personal report.';a.textContent=pt?'Ver Meu Relatório de Tesouros':'View My Treasure Report';a.href='./treasure-report.html';}else{d.textContent=pt?'Conecte sua conta Upland no Dashboard para acessar seu relatório.':'Connect your Upland account in the Dashboard to access your report.';a.textContent=pt?'Conectar conta Upland':'Connect Upland Account';a.href='#dashboard';a.onclick=()=>{window.scrollTo({top:0,behavior:'smooth'});};}}
function init(){addDiscordFooter();loadOnce('directory-navigation.js?v=20260828-stable','nodehub-directory-runtime');loadOnce('nodehub-i18n-lite.js?v=20260828-stable','nodehub-i18n-lite-runtime');setupNodeCarousel();markVerified();addTreasureButton();updateTreasureButton();const o=new MutationObserver(()=>{markVerified();addTreasureButton();updateTreasureButton()});o.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['data-connected']});setTimeout(addDiscordFooter,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();