/* Node Hub - My Treasure Report */
(function(){
 const FUNCTION='https://ynqtzyzxspoxssjrjeve.supabase.co/functions/v1/upland-personal-report';
 const PT=()=>localStorage.getItem('nodehub-language')==='pt-BR';
 const L=()=>PT()?{ey:'TREASURE',title:'Meu Relatório de Tesouros',desc:'Consulte seus resultados de caça diretamente da sua conta Upland.',connect:'Conecte sua conta Upland acima para visualizar seu relatório.',refresh:'Atualizar relatório',loading:'Buscando dados atuais...',updated:'Última atualização',treasures:'Tesouros encontrados',upx:'UPX encontrado',avg:'Média por tesouro',spark:'Sparklet',best:'Maior recompensa',last:'Último tesouro',cities:'Cidades',history:'Histórico recente',empty:'Nenhum resultado de caça encontrado no período.',error:'Não foi possível carregar seu relatório.'}:{ey:'TREASURE',title:'My Treasure Report',desc:'View your treasure hunting results directly from your Upland account.',connect:'Connect your Upland account above to view your report.',refresh:'Refresh report',loading:'Fetching current data...',updated:'Last updated',treasures:'Treasures found',upx:'UPX found',avg:'Average per treasure',spark:'Sparklet',best:'Best reward',last:'Last treasure',cities:'Cities',history:'Recent history',empty:'No treasure hunting results found for this period.',error:'Unable to load your report.'};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const fmt=n=>Number(n||0).toLocaleString(PT()?'pt-BR':'en-US');
 let observer=null;
 function card(){return document.getElementById('my-treasure-report-card')}
 function inject(){const dashboard=document.getElementById('nodehub-user-dashboard');if(!dashboard||card())return;const account=document.getElementById('upland-account-card');if(!account)return;const box=document.createElement('div');box.id='my-treasure-report-card';box.className='auth-card';box.style.cssText='max-width:900px;margin:0 auto 24px';box.innerHTML=`<span class="eyebrow">${L().ey}</span><h2 style="margin-top:8px">${L().title}</h2><p>${L().desc}</p><div id="treasure-report-content"><p style="opacity:.7">${L().connect}</p></div>`;account.insertAdjacentElement('afterend',box);checkConnection();}
 async function checkConnection(){const box=card(),content=document.getElementById('treasure-report-content');if(!box||!content||!window.db)return;try{const r=await db.functions.invoke('upland-connect',{body:{action:'status'}});if(r.data?.status==='connected'){content.innerHTML=`<div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><button id="treasure-report-refresh" class="button button-primary" type="button">${L().refresh}</button><span id="treasure-report-status" style="opacity:.7"></span></div><div id="treasure-report-result" style="margin-top:20px"></div>`;document.getElementById('treasure-report-refresh').onclick=loadReport;return}content.innerHTML=`<p style="opacity:.7">${L().connect}</p>`}catch(e){content.innerHTML=`<p style="opacity:.7">${L().connect}</p>`}}
 async function loadReport(){const b=document.getElementById('treasure-report-refresh'),s=document.getElementById('treasure-report-status'),out=document.getElementById('treasure-report-result');if(!b||!out)return;b.disabled=true;b.textContent=L().loading;if(s)s.textContent='';try{const session=(await db.auth.getSession()).data.session;if(!session)throw new Error('AUTH_REQUIRED');const url=new URL(FUNCTION);url.searchParams.set('period','24h');const r=await fetch(url,{headers:{Authorization:`Bearer ${session.access_token}`,apikey:session.access_token}});const body=await r.json();if(!r.ok||!body.success)throw new Error(body.error||'REPORT_ERROR');render(body,out);if(s)s.textContent=`${L().updated}: ${new Date(body.generatedAt).toLocaleString(PT()?'pt-BR':'en-US')}`}catch(e){console.error('Treasure report:',e);out.innerHTML=`<p style="opacity:.75">${L().error}</p>`}finally{b.disabled=false;b.textContent=L().refresh}}
 function render(body,out){const l=L(),t=body.summary||{},cities=body.cities||[],history=body.history||[];out.innerHTML=`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px"><div class="admin-stat"><span>${l.treasures}</span><strong>${fmt(t.treasures)}</strong></div><div class="admin-stat"><span>${l.upx}</span><strong>${fmt(t.totalUpx)} UPX</strong></div><div class="admin-stat"><span>${l.avg}</span><strong>${fmt(t.avgUpx)} UPX</strong></div><div class="admin-stat"><span>${l.spark}</span><strong>${fmt(t.totalSparklet)}</strong></div><div class="admin-stat"><span>${l.best}</span><strong>${fmt(t.maxReward)} UPX</strong></div></div><div style="margin-top:22px"><strong>${l.last}: </strong>${t.lastTreasure?new Date(t.lastTreasure).toLocaleString(PT()?'pt-BR':'en-US'):'-'}</div>${cities.length?`<div style="margin-top:22px"><h3>${l.cities}</h3><div style="display:grid;gap:8px">${cities.slice(0,8).map((c,i)=>`<div style="display:flex;justify-content:space-between;gap:12px;padding:10px 12px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><span>${i+1}. ${esc(c.city)}</span><span>${fmt(c.hunts)} · ${fmt(c.upx)} UPX</span></div>`).join('')}</div></div>`:''}${history.length?`<div style="margin-top:22px"><h3>${l.history}</h3><div style="display:grid;gap:8px">${history.slice(0,10).map(h=>`<div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:10px 12px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><span>${h.city?esc(h.city):'-'}</span><strong>${fmt(h.upx)} UPX</strong><span style="opacity:.7">${h.rewardTime?new Date(h.rewardTime).toLocaleString(PT()?'pt-BR':'en-US'):'-'}</span></div>`).join('')}</div></div>`:''}${!history.length?`<p style="opacity:.7;margin-top:20px">${l.empty}</p>`:''}`;}
 function watch(){inject();if(observer)observer.disconnect();observer=new MutationObserver(()=>{inject();const box=card();if(box&&!box.dataset.langBound){box.dataset.langBound='1';window.addEventListener('nodehub:language-change',()=>{box.remove();setTimeout(inject,0)})}});observer.observe(document.body,{childList:true,subtree:true})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();