(function(){'use strict';
const SUPA='https://ynqtzyzxspoxssjrjeve.supabase.co';
const KEY='sb_publishable_'+'FoDbr9qgVeeIYfzEZNNN9Q_53aHxI2g';
const db=window.supabase.createClient(SUPA,KEY);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('en-US');
let period='24h';
async function run(){const status=document.getElementById('tr-status');try{const {data:{session}}=await db.auth.getSession();if(!session?.user){status.textContent='Connect your Upland account to view your Treasure Report.';document.getElementById('tr-history').innerHTML='<div class="tr-empty">Please sign in to Node Hub first.</div>';return;}const {data:conn,error}=await db.from('upland_connections').select('upland_user_id,status').eq('user_id',session.user.id).eq('status','connected').maybeSingle();if(error)throw error;if(!conn?.upland_user_id){status.textContent='Connect your Upland account in the Node Hub Dashboard first.';document.getElementById('tr-history').innerHTML='<div class="tr-empty"><a class="button button-primary" href="./index.html#dashboard">Connect Upland Account</a></div>';return;}status.textContent='✓ Upland Account Connected';const endpoint=`${SUPA}/functions/v1/upland-personal-report?upland_user_id=${encodeURIComponent(conn.upland_user_id)}&period=${encodeURIComponent(period)}`;const r=await fetch(endpoint);const data=await r.json();if(!r.ok||!data.success)throw new Error(data.error||`HTTP ${r.status}`);document.getElementById('tr-title').textContent=data.username||'My Treasure Report';const s=data.summary||{};document.getElementById('tr-treasures').textContent=fmt(s.treasures);document.getElementById('tr-upx').textContent=fmt(s.totalUpx)+' UPX';document.getElementById('tr-avg').textContent=fmt(s.avgUpx)+' UPX';document.getElementById('tr-spark').textContent=fmt(s.totalSparklet);document.getElementById('tr-best').textContent=fmt(s.maxReward)+' UPX';document.getElementById('tr-last').textContent=s.lastTreasure?new Date(s.lastTreasure).toLocaleString():'—';const h=data.history||[];document.getElementById('tr-history').innerHTML=h.length?`<table class="tr-table"><thead><tr><th>Time</th><th>UPX</th><th>Sparklets</th><th>City</th></tr></thead><tbody>${h.map(x=>`<tr><td>${esc(new Date(x.rewardTime).toLocaleString())}</td><td>${fmt(x.upx)}</td><td>${fmt(x.sparklet)}</td><td>${esc(x.city||'Unknown')}</td></tr>`).join('')}</tbody></table>`:'<div class="tr-empty">No Treasure events found for this period.</div>';const c=data.cities||[];document.getElementById('tr-cities').innerHTML=c.length?`<table class="tr-table"><thead><tr><th>City</th><th>Hunts</th><th>UPX</th><th>Average</th></tr></thead><tbody>${c.map(x=>`<tr><td>${esc(x.city)}</td><td>${fmt(x.hunts)}</td><td>${fmt(x.upx)}</td><td>${fmt(x.avgUpx)}</td></tr>`).join('')}</tbody></table>`:'<div class="tr-empty">No city data for this period.</div>';}catch(e){console.error('Treasure Report:',e);status.textContent='Unable to load your Treasure Report right now.';document.getElementById('tr-history').innerHTML='<div class="tr-empty">The report could not be loaded. Please try again.</div>';}}
document.querySelectorAll('#tr-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#tr-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');period=b.dataset.period||'24h';run();}));run();
})();